import AppKit
import StripperCore

/// Polls the general pasteboard and replaces copied tracking-laden links with
/// clean ones. macOS has no pasteboard-change notification, so polling the
/// cheap `changeCount` is the standard approach.
@MainActor
final class ClipboardMonitor {
    var onClean: ((CleanResult) -> Void)?
    var isEnabled = true

    private let pasteboard = NSPasteboard.general
    private let cleaner = URLCleaner()
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Types set by password managers and similar apps (nspasteboard.org
    /// conventions). We never touch clipboard content marked with these.
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard isEnabled else { return }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes),
              let string = pasteboard.string(forType: .string),
              let result = cleaner.clean(string)
        else { return }

        pasteboard.clearContents()
        pasteboard.setString(result.cleaned, forType: .string)
        // Also provide a URL flavor so apps that prefer it get the clean link.
        pasteboard.setString(result.cleaned, forType: .URL)
        lastChangeCount = pasteboard.changeCount  // don't re-process our own write
        onClean?(result)
    }
}
